/// Flutter icons GymionIcons_1_1
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GymionIcons_1_1
///      fonts:
///       - asset: fonts/GymionIcons_1_1.ttf
///
///
///
import 'package:flutter/widgets.dart';

class GymionIcons {
  GymionIcons._();

  static const _kFontFam = 'GymionIcons';
  static const String? _kFontPkg = null;

  static const IconData adjust = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aiwave = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowDown = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowLeft = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowRight = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowUp = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData belly = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData body = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cyclist = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbells = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gymMachines = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartbeat = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hips = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData levelEasy = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData levelHard = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData levelMedium = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData libra = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plans = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData po = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData running = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoulders = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signOut = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullBody = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buildMuscle = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arm = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spine = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
