/// Flutter icons GymionIcons_1_0
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GymionIcons_1_0
///      fonts:
///       - asset: fonts/GymionIcons_1_0.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GymionIcons_1_0 {
  GymionIcons_1_0._();

  static const _kFontFam = 'GymionIcons_1_0';
  static const String? _kFontPkg = null;

  static const IconData infoTrainingsmode = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kiAnpassen = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData koordination = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kraft = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maschinentraining = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meinKoerper = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mix = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muskelAufbauen = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pfeil = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pfeilGelb = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plans = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profil = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipeUp = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zeit = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beweglichkeit = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardio = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardio_2 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardio_3 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData einstellungen = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fettVerbrennen = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freieGewichte = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData generelleFitness = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hautStraffen = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
